export const ActionType = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT', 
    SET_CATEGORIES: 'SET_CATEGORIES',
    FILTER_PRODUCTS: 'FILTER_PRODUCTS',
    ADD_PRODUCT_TO_BASKET: 'ADD_PRODUCT_TO_BASKET',
    SET_BASKET_SHOW: 'SET_BASKET_SHOW'
}